/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fi.helsinki.server;

import fi.helsinki.btls.ObservationGenerator;
import fi.helsinki.btls.datamodels.*;
import fi.helsinki.btls.services.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        PropertiesHandler handler = new PropertiesHandler("config/mqttConfig.properties");

        String subscribeTopic = handler.getProperty("subscribeTopic");
        String publishTopic = handler.getProperty("publishTopic");
        String mqttUrl = handler.getProperty("mqttUrl");
        boolean debug = Boolean.parseBoolean(handler.getProperty("debug"));

        IMqttService mqttService = new MqttService(mqttUrl,subscribeTopic,publishTopic);

        int positionsDimension = 3;
        IObserverService observerService = new ObserverService(positionsDimension);
        Map<String, String> allProperties = new PropertiesHandler("config/rasps.properties").getAllProperties();
        List<Observer> all = new ArrayList<>();
        List<String> observerKeys = new ArrayList<>();

        allProperties.forEach((key, value) -> {
            String[] rasp = value.split(":");
            double[] temp = new double[positionsDimension];

            for (int i = 0; i < positionsDimension; i++) {
                temp[i] = Double.parseDouble(rasp[i]);
            }

            Observer obs = new Observer(key);
            obs.setPosition(temp);
            all.add(obs);

            observerKeys.add(key);
        });

        if (!observerService.addAllObservers(all)) {
            return;
        }

        ObservationGenerator obsMock = new ObservationGenerator(12, 30, observerKeys);
        ILocationService service = new LocationService3D(observerService);
        while (true) {
            try {
                Thread.sleep(1000);
                List<Beacon> beacons;

                if (debug) {
                    beacons = obsMock.getBeacons();
                } else {
                    beacons = mqttService.getBeacons();
                }

                List<Location> locations = service.calculateAllLocations(beacons);
                mqttService.publish(locations);
            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
        }
    }
}
